name: notee_mobile
description: "Simple note and task manager."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^3.1.0

flutter:
  uses-material-design: true
